# Generated by Django 3.0.5 on 2020-04-09 08:36

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to=recipe.models.get_recipe_instance_file_path),
        ),
    ]
